# Generated by Django 5.0 on 2023-12-15 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DjangoApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="User",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="client",
            new_name="user",
        ),
    ]
