# Generated by Django 5.0 on 2023-12-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DjangoApp", "0002_rename_client_user_rename_client_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="secret", max_length=255),
        ),
    ]
